### ISSUE TITLE
What repo did you move the qutebrowser package to?

### ISSUE THREAD

**Issue by veilm** [sdsddsd1/kiss-s3d4#1]
On [here](https://github.com/sdsddsd1/kiss-s3d4/commit/f4092d6db2bd769e8c8c45fb1de56e3e5e53cf9e), you said "qutebrowser move to community", but I don't see qutebrowser on https://github.com/kisslinux/community nor https://github.com/kiss-community/community.

Where did it go?

**Comment by sdsddsd1** [comment]
It was moved to community but dropped there aswell.
You can find the commits in community with
```
cd community
git log | grep qute
git show "your commit hash goes here"
```
or the you can view the last commit in this repo where it was dropped with 
```
cd kiss-s3d4
git show f4092d6db2bd769e8c8c45fb1de56e3e5e53cf9e
```
Then a diff is showed with the different bits (py-qt5 py-qtwebengine ......) Surely they must be bumped to match the qt5 version in community.
But heads up, there is currently a blocker building qt5-webengine. https://github.com/kiss-community/community/issues/499
